server.port=8080

# PostgreSQL Configuration (Docker kbase-postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/kbase
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.kbase=DEBUG
logging.level.org.springframework.security=INFO

# Cấu hình gửi mail qua Google SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=accfbclon956@gmail.com
spring.mail.password=xloq otzd xgeo xlsf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true